apiVersion: apps/v1
kind: Deployment
metadata:
  name: fairness-checker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fairness-checker
  template:
    metadata:
      labels:
        app: fairness-checker
    spec:
      containers:
        - name: fairness-checker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
